spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/banksystem
    username: ${DB_USR:postgres}
    password: ${DB_PSW:postgres}
  liquibase:
    change-log: classpath:db/changelog/changelog.xml



